# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='supplier_found',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category_parent',
        ),
        migrations.AlterField(
            model_name='entry',
            name='for_people',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
