# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20161213_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='payment_type',
            field=models.CharField(choices=[('CREDITCARD', 'credit card'), ('VIR', 'transfert'), ('PRLV', 'withdrawal'), ('DAB', 'DAB')], default='', max_length=100, verbose_name='payment type'),
            preserve_default=False,
        ),
    ]
