# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20161013_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='_num_people',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
