# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
    ]
