# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CREDITCARD', 'credit card'), ('VIR', 'transfert'), ('PRLV', 'withdrawal'), ('DAB', 'DAB')], max_length=100, null=True, verbose_name='payment type'),
        ),
    ]
