# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20161215_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.Entry')),
            ],
            bases=('entries.entry',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.Entry')),
            ],
            bases=('entries.entry',),
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-operation_date'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CREDITCARD', 'credit card'), ('VIR', 'transfert'), ('PRLV', 'withdrawal'), ('DAB', 'DAB'), ('CASH', 'CASH')], max_length=100, null=True, verbose_name='payment type'),
        ),
    ]
